# Generated by Django 4.1 on 2022-09-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0002_user_type_payments_disponible_clase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
