# Generated by Django 4.1 on 2022-09-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0003_rename_payments_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='generic_profile_pic.png', upload_to=''),
        ),
    ]
