# Generated by Django 4.1 on 2023-03-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0005_student_teacher_clase_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
